tasks:
  - name: STARTING 
    before: |
      echo "Updating npm"
      npm install -g npm@latest
      echo "Installing tools…"
      npm install -g firebase-tools && @angular/cli
    init: |
      echo "Installing dependencies…"
      npm install
    command: |
      echo "Serve project"
      npm start